---
title: "Final_Project_Complete"
output: html_document
---
Here I am loading the libraries and the data needed for my analysis.
```{r}
library(tidyverse)
library(kableExtra)

emissions <- read_csv("https://raw.githubusercontent.com/npilsbury/jour405_spring25/refs/heads/main/project/Emissions.csv")

wins <- read_csv("https://raw.githubusercontent.com/npilsbury/jour405_spring25/refs/heads/main/project/Project%20Data%20-%20Sheet1.csv")
```

Here I am using the "summary" feature to find the mean, median and standard deviation for the 2023 and 2024 emissions and wins for Big Ten football teams. I am also combing the data into one dataset for future tests.

```{r}
emissions_summary <- emissions %>% mutate(mean_emissions2023 = mean(Emissions2023), median_emissions2023= median(Emissions2023), mean_emissions2024= mean(Emissions2024), median_emissions2024 = median(Emissions2024), sd_emissions2023 = sd(Emissions2023), sd_emissions2024 = sd(Emissions2024))

wins_summary <- wins %>% mutate(mean_wins2023= mean(Wins2023), mean_wins2024 = mean(Wins2024), median_wins2023 = mean(Wins2023), median_wins2024 = median(Wins2024), sd_wins2023 = sd(Wins2023), sd_Wins2024 = sd(Wins2024))

combined <- wins |> inner_join(emissions, join_by(Team))
```
(findings)


Calculating Z-Scores

```{r}
emissions_summary <- emissions_summary |> mutate(z_score = (Emissions2023 - mean_emissions2023) / sd_emissions2023)

emissions_summary |>
  select(Team, Emissions2023, z_score) |>
  head(10) |>
  kable(digits = 2)

emissions_summary <- emissions_summary %>% mutate(z_score = (Emissions2024 - mean_emissions2024) / sd_emissions2024)

emissions_summary |>
  select(Team, Emissions2024, z_score) |>
  head(10) |>
  kable(digits = 2)

wins_summary <- wins_summary %>% mutate(z_score = (Wins2023 - mean_wins2023) / sd_wins2023)

wins_summary |>
  select(Team, Wins2023, z_score) |>
  head(10) |>
  kable(digits = 2)

wins_summary <- wins_summary %>% mutate(z_score = (Wins2024 - mean_wins2024) / sd_Wins2024)

wins_summary |>
  select(Team, Wins2024, z_score) |>
  head(10) |>
  kable(digits = 2)
```
(findings)


Linear Regression

```{r}
combined %>% 
  ggplot(aes(x = `Emissions2023`, y = `Wins2023`)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(x = "Emissions 2023", y = "Wins 2023", title = "Scatterplot of Emissions vs Wins 2023")

model2023 <- lm(`Wins2023` ~ `Emissions2023`, data = combined)
summary(model2023)

combined %>% 
  ggplot(aes(x = `Emissions2024`, y = `Wins2024`)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(x = "Emissions 2024", y = "Wins 2024", title = "Scatterplot of Emissions vs Wins 2024")

model2024 <- lm(`Wins2024` ~ `Emissions2024`, data = combined)
summary(model2024)
```
ANOVA

```{r}
wins <- wins %>% 
  mutate(
    wins2023_category = cut(Wins2023, 
                          breaks = c(-Inf, 3, 7, Inf), 
                          labels = c("Low", "Medium", "High")),
    wins2024_category = cut(Wins2024, 
                          breaks = c(-Inf, 3, 7, Inf), 
                          labels = c("Low", "Medium", "High"))
  )
anova_result_wins <- aov(Wins2024 ~ wins2023_category, data = wins)
summary(anova_result_wins)

```
```{r}
emissions <- emissions %>% 
  mutate(
    emissions2023_category = cut(Emissions2023, 
                          breaks = c(-Inf, 177600, 261700, Inf), 
                          labels = c("Low", "Medium", "High")),
   emissions2024_category = cut(Emissions2024, 
                          breaks = c(-Inf,177600, 261700, Inf), 
                          labels = c("Low", "Medium", "High"))
  )
anova_result_emissions <- aov(Emissions2024 ~ emissions2023_category, data = emissions)
summary(anova_result_emissions)
```
Tukey Test
```{r}
TukeyHSD(anova_result_wins)
```
```{r}
TukeyHSD(anova_result_emissions)
```

